### ISSUE TITLE
nendSDK-Unity バナー広告でのイベントハンドラーの使い方

### ISSUE THREAD

**Issue by takuyayoneda** [fan-ADN/nendSDK-Unity#2]
nendSDK-Unityのバナー広告クリックでイベントを発生させようとしているのですが、イベントハンドラーをうまく使えません。
具体的なコードは、
public class game: MonoBehaviour {
private bool ｓtatus;
NendAdBanner bannerClick = bannerClick.AdClicked += OnClickBannerAd;
public void OnClickBannerAd (object sender, EventArgs args)
    {
        UnityEngine.Debug.Log ("広告がクリックされました。");
        ｓtatus = true;
    }
｝

とすると、
error CS0236: A field initializer cannot reference the nonstatic field, method, or property `game.OnClickBannerAd(object, System.EventArgs)'

というエラーが出てしまいます。
とても初歩的な知識不足ではないかとは思うのですが・・・
解決方法ご存知の方いらっしゃいましたらご教示をお願いいたします。

**Comment by ghost** [comment]
@takuyayoneda 様

お問い合わせいただきありがとうございます。

``` C#
NendAdBanner bannerClick = bannerClick.AdClicked += OnClickBannerAd;
```

上記のコードでエラーとなっているようです。

`bannerClick`変数に`NendAdBanner`のインスタンスをセットしてから`AdClicked`イベントを登録するよう実装してみてください。

以下、簡単な実装例となります。

``` C#
public class game: MonoBehaviour {

    public NendAdBanner bannerClick;

    void Start() {
        // GetComponent等でNendAdBannerのインスタンスを取得します。
        // http://docs.unity3d.com/jp/current/ScriptReference/GameObject.GetComponent.html
        // あるいはInspector上でbannerClickにNendAdBannerを割り当てておきます
        // http://docs.unity3d.com/ja/current/Manual/EditingValueProperties.html
        bannerClick = ...;
        ...

        // イベントの登録
        bannerClick.AdClicked += OnClickBannerAd;
    } 
}
```

よろしくお願い致します。

**Comment by takuyayoneda** [comment]
ご回答ありがとうございます。

恥ずかしい質問だと思うのですが、

// GetComponent等でNendAdBannerのインスタンスを取得します

という部分で具体的なコードは、

NendAdBanner bannerClick =
gameObject.GetComponentInParent(typeof(NendAdBanner)) as NendAdBanner;

で大丈夫でしょうか？

また、

bannerClick = ...;

...

の　･･･　の部分には何が入るのでしょうか？

ご存知の方にとっては当たり前のことなのだと思いますが、うまく動作させられないので

大変申し訳ありませんがご教示お願いいたします。

2016年8月29日 9:58 fan-k-manabe notifications@github.com:

**Comment by ghost** [comment]
@takuyayoneda 様

お世話になっております。
以下、インラインで失礼いたします。

> という部分で具体的なコードは、
> NendAdBanner bannerClick =
> gameObject.GetComponentInParent(typeof(NendAdBanner)) as NendAdBanner;
> で大丈夫でしょうか？

`GetComponent`系メソッドの使い方は、アプリ側の実装方法によって変わってきます。
`game`という名称のスクリプトが割り当てられている`GameObject`の親オブジェクトに`NendAdBanner`が割り当てられている場合は、上記のコードで取得できると思います。
また、`NendAdBanner`が割り当てられている`GameObject`に`game`も割り当てられている場合は、以下のようなコードからもインスタンスを取得できます。

``` C#
public class game: MonoBehaviour {

    public NendAdBanner bannerClick;

    void Start() {
        bannerClick = gameObject.GetComponent <NendAdBanner> ();
    } 
}
```

**詳細に関しましては、恐れ入りますがUnityのスクリプトリファレンスや弊社のサンプルアプリ等でご確認ください。**

> の　･･･　の部分には何が入るのでしょうか？

一つ目は`NendAdBanner`を取得するコードが入ります。
二つ目は省略の意味合いで記載しただけとなりますので、無視していただいて構いません。

よろしくお願い致します。

**Comment by takuyayoneda** [comment]
ありがとうございます。

いつもとても助かります！

2016年8月30日 10:22 fan-k-manabe notifications@github.com:

**Comment by ghost** [comment]
@takuyayoneda 様

こちらのissueはクローズしてしまってもよろしいでしょうか？

**Comment by takuyayoneda** [comment]
$B$9$_$^$;$s!"$3$A$i$KB3$-$G=q$$$?J}$,NI$+$C$?$G$9$M!#(B
$B%/%m!<%:$7$F9=$$$^$;$s!#(B
$B$_<j?t$r$_$+$1$7$F?=$7Lu$4$6$$$^$;$s!#(B

iPhone$B$+$iAw?.(B

2016/09/28 12:39$B!"(Bfan-k-manabe notifications@github.com $B$N%a%C%;!<%8(B:
