### ISSUE TITLE
nendSDK-Unity のバナー広告クリックイベントを利用する方法

### ISSUE THREAD

**Issue by takuyayoneda** [fan-ADN/nendSDK-Unity#3]

**Comment by takuyayoneda** [comment]
Unity5.3.5f1で簡単なandroid端末用ゲームを作成しています。
OnClickBannerAd（）｛　｝ 内にadStatus=trueを記述してバナー広告のクリックがあったときにadStatusをtrueにしようとしていますが、端末にインストールしてバナーをクリックしてもtrueになりません。
どうすればバナーのクリックイベントをゲーム内で利用できるでしょうか？

public class game: MonoBehaviour {
    NendAdBanner bannerClick;
public void OnClickBannerAd (object sender, EventArgs args){
        adStatus = true;
    }
public void Start (){
bannerClick = gameObject.GetComponent<NendAdBanner>();
bannerClick.AdClicked += OnClickBannerAd;
bannerClick.Show();
｝
･･･
｝

**Comment by ghost** [comment]
@takuyayoneda 様

お世話になっております。

``` c#
bannerClick = gameObject.GetComponent();
```

ここで`NendAdBanner`のインスタンスが正しく取得できているかご確認いただけますでしょうか？

**Comment by takuyayoneda** [comment]
fan-k-manabe様

ご回答ありがとうございます。

bannerClick = gameObject.GetComponent(NendAdBanner);

の後に、

bannerClick.show();

を入れるとバナー（現在テスト用を使用中）が表示されますので、取得

できていると思うのですがこの考え正しいでしょうか・・・？

もし違っていたら、どうやって正しく取得されていることを確認すれば

いいでしょうか？

何度もすみません、ご教示お願いします。

2016-09-28 12:38 GMT+09:00 fan-k-manabe notifications@github.com:

**Comment by ghost** [comment]
@takuyayoneda 様

ご回答ありがとうございます。
以下、インラインで失礼いたします。

> bannerClick.show();
> を入れるとバナー（現在テスト用を使用中）が表示されますので、取得
> できていると思うのですがこの考え正しいでしょうか・・・？

Inspector上で`NendAdBanner`の`Automatic Display`にチェックが入っている場合は、`show()`メソッドを呼び出さずとも広告は自動的に表示されます。したがって、もし`Automatic Display`のチェックを外されている場合は、インスタンスの取得は問題なく行われているということになります。

> もし違っていたら、どうやって正しく取得されていることを確認すれば
> いいでしょうか？

例として以下のような方法で確認可能かと存じます。
- デバッガで`gameObject.GetComponent()`の後に`bannerClick`に`NendAdBanner`のインスタンスが格納できているか確認する
- `gameObject.GetComponent()`の後に`bannerClick`インスタンスをログに出力する

**Comment by takuyayoneda** [comment]
fan-k-manabe$BMM(B

$B$42sEz$"$j$,$H$&$4$6$$$^$9!#(B

inspector$B>e$N%A%'%C%/$r30$7$?>uBV$G%P%J!<$,I=<($5$l$k$N$G!"%$%s%9%?%s%9$N<hF@$OBg>fIW$N$h$&$G$9!#(B

$B;H$$J}$NLdBj$G$7$g$&$+!&!&(B


iPhone$B$+$iAw?.(B

2016/09/29 10:08$B!"(Bfan-k-manabe <notifications@github.com> $B$N%a%C%;!<%8(B:

**Comment by takuyayoneda** [comment]
fan-k-manabe様
ご回答ありがとうございます。

現在のようにバナークリックのイベントハンドラー内でゲームシーンのスクリプトの変数を変える方法ですと、
広告が表示された後にandroidのbackボタンなどでゲームに戻ると再度ゲームシーンのリロードのときに
変数が初期化されてしまいます。

バナークリックのイベントハンドラーで変更したゲーム内の変数が、広告表示後のゲームシーンのリロード後も
維持される方法をいくつかご紹介いただけないでしょうか・・・？

2016年9月29日 20:21 t.yoneda iiw.create01@gmail.com:

**Comment by ghost** [comment]
@takuyayoneda 様

お世話になっております。

> バナークリックのイベントハンドラーで変更したゲーム内の変数が、広告表示後のゲームシーンのリロード後も維持される方法をいくつかご紹介いただけないでしょうか・・・？

恐れ入りますが、上記はnendSDKではなくUnityの実装に関する内容となりますので、こちらからはお答えいたしかねます。Unityのデベロッパーリファレンスやネットの情報等でご確認ください。

お力になれず申し訳ございませんが、ご了承の程よろしくお願い申し上げます。

**Comment by takuyayoneda** [comment]
fan-k-manabe様
いつもありがとうございます。
確かに、質問内容がそれてしまい大変失礼いたしました。
今後ともよろしくお願いいたします。

**Comment by takuyayoneda** [comment]
度々申し訳ございません。
以下のスクリプトgameをNendAdBannerと同じゲームオブジェクトにアタッチしています。
バナーをクリックするとcountが0になり、PlayerPrefsのcountも0になって欲しいのですが
アンドロイド端末でバナーをクリックし、広告画面から戻るボタンでゲーム画面に戻ると
どちらのcountも0になっていません。
バナークリックのイベントハンドラーの使い方として間違っていますでしょうか？

public class game: MonoBehaviour {
        NendAdBanner bannerClick;
        public int count;
        public void OnClickBannerAd (object sender, EventArgs args){
        count = 0;
        PlayerPrefs.SetInt("count", 0);
    }
        public void Start (){
        count = PlayerPrefs.GetInt("count");
        bannerClick = gameObject.GetComponent<NendAdBanner>();
        bannerClick.AdClicked += OnClickBannerAd;
        bannerClick.Show();
    }
        void Update () {
        if(Input.anyKeyDown && count < 3){
            status++;
        }
                if(status > 4){
                        status = 0;
            count++;
            PlayerPrefs.SetInt("count" , count);
        }
        }
}

**Comment by ghost** [comment]
@takuyayoneda 様

お世話になっております。

回答が遅くなってしまい申し訳ございませんでした。

> バナークリックのイベントハンドラーの使い方として間違っていますでしょうか？

こちらですが、特に間違いはないかと存じます。

以上、よろしくお願い致します。

**Comment by takuyayoneda** [comment]
fan-k-manabe様

ご回答ありがとうございます。

2016年10月11日 9:56 fan-k-manabe notifications@github.com:
