### ISSUE TITLE
CommandInvokationFailure: Failed to re-package resources

### ISSUE THREAD

**Issue by diego-coronado** [fan-ADN/nendSDK-Unity#5]
I am trying to create a project using the latest version of nendad in Unity 5.6.6 and the project right now only has en empty scene and the nendsdk plugin. When I try to build the project this error shows up

`CommandInvokationFailure: Failed to re-package resources.
C:\Users\DC\AppData\Local\Android\sdk\build-tools\23.0.3\aapt.exe package --auto-add-overlay -v -f -m -J "gen" -M "AndroidManifest.xml" -S "res" -I "C:/Users/DC/AppData/Local/Android/sdk\platforms\android-25\android.jar" -F bin/resources.ap_ --extra-packages android.arch.core:android.arch.lifecycle.livedata.core:android.arch.lifecycle:android.arch.lifecycle.viewmodel:android.support.v7.cardview:android.support.constraint:android.support.v7.recyclerview:android.support.compat:android.support.coreui:android.support.coreutils:android.support.fragment:android.support.mediacompat:android.support.v4:com.google.android.gms.base:com.google.android.gms.base.license:com.google.android.gms:com.google.android.gms.common.license:com.google.android.gms.location:com.google.android.gms.location.license:com.google.android.gms.tasks:com.google.android.gms.tasks.license:net.nend.unity.plugin:net.nend.android -S "D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\android.arch.core.runtime-1.1.0\res" -S "D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\android.arch.lifecycle.livedata-core-1.1.0\res" -S "D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\android.arch.lifecycle.runtime-1.1.0\res" -S "D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\android.arch.lifecycle.viewmodel-1.1.0\res" -S "D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.cardview-v7-27.1.0\res" -S "D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.constraint.constraint-layout-1.0.2\res" -S "D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.recyclerview-v7-27.1.0\res" -S "D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-compat-27.1.0\res" -S "D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-core-ui-27.1.0\res" -S "D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-core-utils-27.1.0\res" -S "D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-fragment-27.1.0\res" -S "D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.0\res" -S "D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-v4-27.1.0\res" -S "D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.google.android.gms.play-services-base-11.8.0\res" -S "D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.google.android.gms.play-services-basement-11.8.0\res" -S "D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.google.android.gms.play-services-location-11.8.0\res" -S "D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.google.android.gms.play-services-tasks-11.8.0\res" -S "D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\nend-unity-plugin\res" -S "D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\nendSDK-4.0.5\res"

stderr[
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-compat-27.1.0\res\layout\notification_action.xml:17: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <LinearLayout>
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-compat-27.1.0\res\layout\notification_action.xml:32: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <TextView>
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-compat-27.1.0\res\layout\notification_action.xml: note: using v17 attributes; synthesizing resource com.ddfe.ggg:layout/notification_action for configuration v17.
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-compat-27.1.0\res\layout\notification_action_tombstone.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <LinearLayout>
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-compat-27.1.0\res\layout\notification_action_tombstone.xml:37: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <TextView>
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-compat-27.1.0\res\layout\notification_action_tombstone.xml: note: using v17 attributes; synthesizing resource com.ddfe.ggg:layout/notification_action_tombstone for configuration v17.
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.0\res\layout\notification_template_big_media.xml:42: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.0\res\layout\notification_template_big_media.xml:34: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <include>
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.0\res\layout\notification_template_big_media.xml:34: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <include>
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.0\res\layout\notification_template_big_media.xml:27: note: removing attribute http://schemas.android.com/apk/res/android:layout_alignParentEnd from <include>
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.0\res\layout\notification_template_big_media.xml: note: using v17 attributes; synthesizing resource com.ddfe.ggg:layout/notification_template_big_media for configuration v17.
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.0\res\layout\notification_template_big_media_custom.xml:89: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.0\res\layout\notification_template_big_media_custom.xml:34: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <LinearLayout>
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.0\res\layout\notification_template_big_media_custom.xml:34: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <LinearLayout>
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.0\res\layout\notification_template_big_media_custom.xml:56: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <FrameLayout>
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.0\res\layout\notification_template_big_media_custom.xml:45: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <FrameLayout>
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.0\res\layout\notification_template_big_media_custom.xml:45: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <FrameLayout>
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.0\res\layout\notification_template_big_media_custom.xml:27: note: removing attribute http://schemas.android.com/apk/res/android:layout_alignParentEnd from <include>
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.0\res\layout\notification_template_big_media_custom.xml: note: using v17 attributes; synthesizing resource com.ddfe.ggg:layout/notification_template_big_media_custom for configuration v17.
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.0\res\layout\notification_template_big_media_narrow.xml:60: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <ImageView>
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.0\res\layout\notification_template_big_media_narrow.xml:46: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <LinearLayout>
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.0\res\layout\notification_template_big_media_narrow.xml:46: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.0\res\layout\notification_template_big_media_narrow.xml:38: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <include>
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.0\res\layout\notification_template_big_media_narrow.xml:38: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <include>
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.0\res\layout\notification_template_big_media_narrow.xml:30: note: removing attribute http://schemas.android.com/apk/res/android:layout_alignParentEnd from <include>
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.0\res\layout\notification_template_big_media_narrow.xml: note: using v17 attributes; synthesizing resource com.ddfe.ggg:layout/notification_template_big_media_narrow for configuration v17.
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.0\res\layout\notification_template_big_media_narrow_custom.xml:107: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <ImageView>
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.0\res\layout\notification_template_big_media_narrow_custom.xml:93: note: removing attribute http://schemas.android.com/apk/res/android:layout_toEndOf from <LinearLayout>
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.0\res\layout\notification_template_big_media_narrow_custom.xml:93: note: removing attribute http://schemas.android.com/apk/res/android:layoutDirection from <LinearLayout>
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.0\res\layout\notification_template_big_media_narrow_custom.xml:38: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <LinearLayout>
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.0\res\layout\notification_template_big_media_narrow_custom.xml:38: note: removing attribute http://schemas.android.com/apk/res/android:layout_toStartOf from <LinearLayout>
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.0\res\layout\notification_template_big_media_narrow_custom.xml:59: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <FrameLayout>
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.0\res\layout\notification_template_big_media_narrow_custom.xml:49: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <FrameLayout>
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.0\res\layout\notification_template_big_media_narrow_custom.xml:49: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <FrameLayout>
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.0\res\layout\notification_template_big_media_narrow_custom.xml:30: note: removing attribute http://schemas.android.com/apk/res/android:layout_alignParentEnd from <include>
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-27.1.0\res\layout\notification_template_big_media_narrow_custom.xml: note: using v17 attributes; synthesizing resource com.ddfe.ggg:layout/notification_template_big_media_narrow_custom for configuration v17.
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-compat-27.1.0\res\layout\notification_template_custom_big.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:paddingEnd from <LinearLayout>
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-compat-27.1.0\res\layout\notification_template_custom_big.xml:32: note: removing attribute http://schemas.android.com/apk/res/android:paddingStart from <FrameLayout>
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-compat-27.1.0\res\layout-v16\notification_template_custom_big.xml:103: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <LinearLayout>
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-compat-27.1.0\res\layout-v16\notification_template_custom_big.xml:95: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <ImageView>
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-compat-27.1.0\res\layout-v16\notification_template_custom_big.xml:32: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart from <LinearLayout>
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-compat-27.1.0\res\layout-v16\notification_template_custom_big.xml:51: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginEnd from <FrameLayout>
D:\Unity Projects\testnendad\testnendad\Temp\StagingArea\android-libraries\com.android.support.support-compat-27.1.0\res\layout-v16\notification_template_custom_big.xml:82: note: removing attribute http://schemas.android.com/apk/res/android:layout_marginStart`

I have sdk-tools version 23.0.3 and have tried with almost every version until 28

**Comment by ghost** [comment]
Hi, @diego-coronado 

It seems to your `Target API Level` is older than our recommend Android Support Library version.

Please upgrade `Target API Level` to `27` or latest on your Unity player settings. That is our recommend option.
Or, if you want to use `Target API Level 23`, please edit following settings : 

1. Remove all build caches
2. Edit every single Android Support Library to older version via `Assets/NendAd/Editor/NendAndroidDependenciesResolver.cs` like below.
    ```csharp
    svcSupport.DependOn(AndroidLibraryTypeSupport, HogeFuga, "27.1.1"); //before
    svcSupport.DependOn(AndroidLibraryTypeSupport, HogeFuga, "23.0.3"); //after
    ```
    Note : And maybe should change to older Google Play Service(`AndroidLibraryTypeGoogle`) what released near season.
3. Resolve dependencies via Play Services Resolver.

Best regards

**Comment by diego-coronado** [comment]
Thank you this worked.
